// lib/flashcardData.ts

export const SAMPLE_DECKS = [
    {
        title: 'SỐ ĐẾM & LƯỢNG TỪ',
        description: 'Các số đếm cơ bản, số đếm vật nhỏ, mỏng, máy móc và tỷ lệ.',
        cards: [
            { front: '一つ', back: 'ひとつ (hitotsu)', example: 'Một cái / Một chiếc' },
            { front: '二つ', back: 'ふたつ (futatsu)', example: 'Hai cái' },
            { front: '三つ', back: 'みっつ (mittsu)', example: 'Ba cái' },
            { front: '四つ', back: 'よっつ (yottsu)', example: 'Bốn cái' },
            { front: '五つ', back: 'いつつ (itsutsu)', example: 'Năm cái' },
            { front: '六つ', back: 'むっつ (muttsu)', example: 'Sáu cái' },
            { front: '七つ', back: 'ななつ (nanatsu)', example: 'Bảy cái' },
            { front: '八つ', back: 'やっつ (yattsu)', example: 'Tám cái' },
            { front: '九つ', back: 'ここのつ (kokonotsu)', example: 'Chín cái' },
            { front: '十', back: 'とお (too)', example: 'Mười cái' },
            { front: 'いくつ', back: 'いくつ (ikutsu)', example: 'Mấy cái, bao nhiêu cái?' },
            { front: '百', back: 'ひゃく (hyaku)', example: '100' },
            { front: '二百', back: 'にひゃく (nihyaku)', example: '200' },
            { front: '三百', back: 'さんびゃく (sanbyaku)', example: '300' },
            { front: '六百', back: 'ろっぴゃく (roppyaku)', example: '600' },
            { front: '八百', back: 'はっぴゃく (happyaku)', example: '800' },
            { front: '千', back: 'せん (sen)', example: '1000' },
            { front: '三千', back: 'さんぜん (sanzen)', example: '3000' },
            { front: '八千', back: 'はっせん (hassen)', example: '8000' },
            { front: '万', back: 'まん (man)', example: '1 vạn (10.000)' },
            { front: '千万', back: 'せんまん (senman)', example: '10 triệu' },
            { front: '~回', back: 'かい (kai)', example: '~ lần' },
            { front: '~台', back: 'だい (dai)', example: '~ chiếc / cỗ (đếm máy móc, xe cộ)' },
            { front: '~枚', back: 'まい (mai)', example: '~ tờ / tấm (đếm vật mỏng)' },
            { front: '~人', back: 'にん (nin)', example: '~ người (VD: 三人 - 3 người)' },
            { front: '半分', back: 'はんぶん (hanbun)', example: 'Một nửa' },
            { front: '四分の一', back: 'よんぶんのいち (yonbun no ichi)', example: '1/4' },
        ]
    },
    {
        title: 'THỜI GIAN & THỜI TIẾT',
        description: 'Ngày trong tháng, thứ trong tuần, các mùa và hiện tượng thời tiết.',
        cards: [
            { front: '一日', back: 'ついたち (tsuitachi)', example: 'Mùng 1' },
            { front: '二日', back: 'ふつか (futsuka)', example: 'Mùng 2' },
            { front: '三日', back: 'みっか (mikka)', example: 'Mùng 3' },
            { front: '四日', back: 'よっか (yokka)', example: 'Mùng 4' },
            { front: '五日', back: 'いつか (itsuka)', example: 'Mùng 5' },
            { front: '六日', back: 'むいか (muika)', example: 'Mùng 6' },
            { front: '七日', back: 'なのか (nanoka)', example: 'Mùng 7' },
            { front: '八日', back: 'ようか (youka)', example: 'Mùng 8' },
            { front: '九日', back: 'ここのか (kokonoka)', example: 'Mùng 9' },
            { front: '十日', back: 'とおか (tooka)', example: 'Mùng 10' },
            { front: '十四日', back: 'じゅうよっか (juuyokka)', example: 'Ngày 14' },
            { front: '二十日', back: 'はつか (hatsuka)', example: 'Ngày 20' },
            { front: '二十四日', back: 'にじゅうよっか (nijuuyokka)', example: 'Ngày 24' },
            { front: '何日', back: 'なんにち (nannichi)', example: 'Ngày mấy, bao nhiêu ngày' },
            { front: '月曜日', back: 'げつようび (getsuyoubi)', example: 'Thứ 2' },
            { front: '火曜日', back: 'かようび (kayoubi)', example: 'Thứ 3' },
            { front: '水曜日', back: 'すいようび (suiyoubi)', example: 'Thứ 4' },
            { front: '木曜日', back: 'もくようび (mokuyoubi)', example: 'Thứ 5' },
            { front: '金曜日', back: 'きんようび (kinyoubi)', example: 'Thứ 6' },
            { front: '土曜日', back: 'どようび (doyoubi)', example: 'Thứ 7' },
            { front: '日曜日', back: 'にちようび (nichiyoubi)', example: 'Chủ nhật' },
            { front: '何曜日', back: 'なんようび (nanyoubi)', example: 'Thứ mấy' },
            { front: '今日', back: 'きょう (kyou)', example: 'Hôm nay' },
            { front: '明日', back: 'あした (ashita)', example: 'Ngày mai' },
            { front: '昨日', back: 'きのう (kinou)', example: 'Hôm qua' },
            { front: '今週', back: 'こんしゅう (konshuu)', example: 'Tuần này' },
            { front: '先週', back: 'せんしゅう (senshuu)', example: 'Tuần trước' },
            { front: '来週', back: 'らいしゅう (raishuu)', example: 'Tuần sau' },
            { front: '毎週', back: 'まいしゅう (maishuu)', example: 'Mỗi tuần' },
            { front: '今月', back: 'こんげつ (kongetsu)', example: 'Tháng này' },
            { front: '先月', back: 'せんげつ (sengetsu)', example: 'Tháng trước' },
            { front: '来月', back: 'らいげつ (raigetsu)', example: 'Tháng sau' },
            { front: '毎月', back: 'まいつき (maitsuki)', example: 'Mỗi tháng' },
            { front: '今年', back: 'ことし (kotoshi)', example: 'Năm nay' },
            { front: '去年', back: 'きょねん (kyonen)', example: 'Năm ngoái' },
            { front: '来年', back: 'らいねん (rainen)', example: 'Năm sau' },
            { front: '再来年', back: 'さらいねん (sarainen)', example: 'Năm sau nữa' },
            { front: '毎年', back: 'まいとし (maitoshi)', example: 'Mỗi năm' },
            { front: '春', back: 'はる (haru)', example: 'Mùa xuân' },
            { front: '夏', back: 'なつ (natsu)', example: 'Mùa hè' },
            { front: '秋', back: 'あき (aki)', example: 'Mùa thu' },
            { front: '冬', back: 'ふゆ (fuyu)', example: 'Mùa đông' },
            { front: '季節', back: 'きせつ (kisetsu)', example: 'Mùa' },
            { front: '時間', back: 'じかん (jikan)', example: 'Thời gian' },
            { front: '~週間', back: 'しゅうかん (shuukan)', example: '~ tuần' },
            { front: '~ヶ月', back: 'かげつ (kagetsu)', example: '~ tháng' },
            { front: '半年', back: 'はんとし (hantoshi)', example: 'Nửa năm' },
            { front: '昼間', back: 'ひるま (hiruma)', example: 'Ban ngày, trưa' },
            { front: '夕方', back: 'ゆうがた (yuugata)', example: 'Chiều tối' },
            { front: '今', back: 'いま (ima)', example: 'Bây giờ' },
            { front: '天気', back: 'てんき (tenki)', example: 'Thời tiết' },
            { front: '雨', back: 'あめ (ame)', example: 'Mưa' },
            { front: '雪', back: 'ゆき (yuki)', example: 'Tuyết' },
            { front: '雲', back: 'くも (kumo)', example: 'Mây' },
        ]
    },
    {
        title: 'CON NGƯỜI & GIA ĐÌNH',
        description: 'Các đại từ nhân xưng, thành viên gia đình và các nghề nghiệp phổ biến.',
        cards: [
            { front: '私', back: 'わたし (watashi)', example: 'Tôi' },
            { front: '私たち', back: 'わたしたち (watashitachi)', example: 'Chúng tôi' },
            { front: 'あなた', back: 'あなた (anata)', example: 'Bạn, anh/chị' },
            { front: '彼 / 彼氏', back: 'かれ / かれし (kare / kareshi)', example: 'Anh ấy, bạn trai' },
            { front: '彼女', back: 'かのじょ (kanojo)', example: 'Cô ấy, bạn gái' },
            { front: '誰 / どなた', back: 'だれ / どなた (dare / donata)', example: 'Ai / Vị nào (lịch sự)' },
            { front: '皆さん', back: 'みなさん (minasan)', example: 'Mọi người, các bạn' },
            { front: 'あの人 / あの方', back: 'あのひと / あのかた (ano hito / ano kata)', example: 'Người kia / Vị kia' },
            { front: '僕', back: 'ぼく (boku)', example: 'Tôi, tớ (nam dùng)' },
            { front: '君', back: 'きみ (kimi)', example: 'Cậu, bạn' },
            { front: '父', back: 'ちち (chichi)', example: 'Bố (của mình)' },
            { front: '母', back: 'はは (haha)', example: 'Mẹ (của mình)' },
            { front: '兄', back: 'あに (ani)', example: 'Anh trai' },
            { front: '姉', back: 'あね (ane)', example: 'Chị gái' },
            { front: '弟', back: 'おとうと (otouto)', example: 'Em trai' },
            { front: '妹', back: 'いもうと (imouto)', example: 'Em gái' },
            { front: '夫 / 主人', back: 'おっと / しゅじん (otto / shujin)', example: 'Chồng' },
            { front: '妻 / 家内', back: 'つま / かない (tsuma / kanai)', example: 'Vợ' },
            { front: '息子', back: 'むすこ (musuko)', example: 'Con trai' },
            { front: '娘', back: 'むすめ (musume)', example: 'Con gái' },
            { front: '祖父', back: 'そふ (sofu)', example: 'Ông' },
            { front: '祖母', back: 'そぼ (sobo)', example: 'Bà' },
            { front: '両親', back: 'りょうしん (ryoushin)', example: 'Bố mẹ' },
            { front: '兄弟', back: 'きょうだい (kyoudai)', example: 'Anh chị em' },
            { front: 'お父さん', back: 'おとうさん (otousan)', example: 'Bố (người khác/xưng hô)' },
            { front: 'お母さん', back: 'おかあさん (okaasan)', example: 'Mẹ (người khác/xưng hô)' },
            { front: 'お兄さん', back: 'おにいさん (oniisan)', example: 'Anh trai (người khác/xưng hô)' },
            { front: 'お姉さん', back: 'おねえさん (oneesan)', example: 'Chị gái (người khác/xưng hô)' },
            { front: 'ご主人', back: 'ごしゅじん (goshujin)', example: 'Chồng (người khác)' },
            { front: '奥さん', back: 'おくさん (okusan)', example: 'Vợ (người khác)' },
            { front: 'お子さん', back: 'おこさん (okosan)', example: 'Con (người khác)' },
            { front: 'おじいちゃん', back: 'おじいちゃん (ojiichan)', example: 'Ông' },
            { front: 'おばあちゃん', back: 'おばあちゃん (obaachan)', example: 'Bà' },
            { front: '先生', back: 'せんせい (sensei)', example: 'Thầy cô giáo' },
            { front: '教師', back: 'きょうし (kyoushi)', example: 'Giáo viên' },
            { front: '学生', back: 'がくせい (gakusei)', example: 'Học sinh, sinh viên' },
            { front: '留学生', back: 'りゅうがくせい (ryuugakusei)', example: 'Du học sinh' },
            { front: '会社員', back: 'かいしゃいん (kaishain)', example: 'Nhân viên công ty' },
            { front: '社員', back: 'しゃいん (shain)', example: 'Nhân viên' },
            { front: '銀行員', back: 'ぎんこういん (ginkouin)', example: 'Nhân viên ngân hàng' },
            { front: '医者', back: 'いしゃ (isha)', example: 'Bác sĩ' },
            { front: '歯医者', back: 'はいしゃ (haisha)', example: 'Nha sĩ' },
            { front: '研究者', back: 'けんきゅうしゃ (kenkyuusha)', example: 'Nhà nghiên cứu' },
            { front: '運転手', back: 'うんてんしゅ (untenshu)', example: 'Tài xế' },
            { front: 'エンジニア', back: 'エンジニア (enjinia)', example: 'Kỹ sư' },
            { front: '社長', back: 'しゃちょう (shachou)', example: 'Giám đốc' },
            { front: '部長', back: 'ぶちょう (buchou)', example: 'Trưởng phòng' },
            { front: '課長', back: 'かちょう (kachou)', example: 'Tổ trưởng' },
            { front: '子供', back: 'こども (kodomo)', example: 'Trẻ em' },
            { front: '大人', back: 'おとな (otona)', example: 'Người lớn' },
            { front: '男の人', back: 'おとこのひと (otoko no hito)', example: 'Người đàn ông' },
            { front: '女の人', back: 'おんなのひと (onna no hito)', example: 'Người phụ nữ' },
            { front: '恋人', back: 'こいびと (koibito)', example: 'Người yêu' },
        ]
    },
    {
        title: 'ĐỒ VẬT & ẨM THỰC',
        description: 'Vật dụng cá nhân, văn phòng phẩm và các loại thực phẩm hằng ngày.',
        cards: [
            { front: 'これ / それ / あれ', back: 'これ / それ / あれ (kore / sore / are)', example: 'Cái này / Cái đó / Cái kia' },
            { front: '携帯', back: 'けいたい (keitai)', example: 'Điện thoại di động' },
            { front: '電話', back: 'でんわ (denwa)', example: 'Điện thoại' },
            { front: 'パソコン', back: 'パソコン (pasokon)', example: 'Máy tính' },
            { front: 'カメラ', back: 'カメラ (kamera)', example: 'Máy ảnh' },
            { front: 'テレビ', back: 'テレビ (terebi)', example: 'Tivi' },
            { front: '時計', back: 'とけい (tokei)', example: 'Đồng hồ' },
            { front: '傘', back: 'かさ (kasa)', example: 'Ô, dù' },
            { front: '鞄', back: 'かばん (kaban)', example: 'Cặp sách, túi' },
            { front: '靴', back: 'くつ (kutsu)', example: 'Giày' },
            { front: '靴下', back: 'くつした (kutsushita)', example: 'Tất' },
            { front: '財布', back: 'さいふ (saifu)', example: 'Ví' },
            { front: '鍵', back: 'かぎ (kagi)', example: 'Chìa khóa' },
            { front: '椅子', back: 'いす (isu)', example: 'Ghế' },
            { front: '机', back: 'つくえ (tsukue)', example: 'Bàn' },
            { front: '本', back: 'ほん (hon)', example: 'Sách' },
            { front: '辞書', back: 'じしょ (jisho)', example: 'Từ điển' },
            { front: 'ノート', back: 'ノート (nooto)', example: 'Vở' },
            { front: '手帳', back: 'てちょう (techou)', example: 'Sổ tay' },
            { front: '新聞', back: 'しんぶん (shinbun)', example: 'Báo' },
            { front: '雑誌', back: 'ざっし (zasshi)', example: 'Tạp chí' },
            { front: '鉛筆', back: 'えんぴつ (enpitsu)', example: 'Bút chì' },
            { front: 'ボールペン', back: 'ボールペン (boorupen)', example: 'Bút bi' },
            { front: '消しゴム', back: 'けしごむ (keshigomu)', example: 'Cục tẩy' },
            { front: '名刺', back: 'めいし (meishi)', example: 'Danh thiếp' },
            { front: '手紙', back: 'てがみ (tegami)', example: 'Thư' },
            { front: '切手', back: 'きって (kitte)', example: 'Tem' },
            { front: 'お金', back: 'おかね (okane)', example: 'Tiền' },
            { front: '細かいお金', back: 'こまかいおかね (komakai okane)', example: 'Tiền lẻ' },
            { front: '現金', back: 'げんきん (genkin)', example: 'Tiền mặt' },
            { front: '荷物', back: 'にもつ (nimotsu)', example: 'Hành lý' },
            { front: '服 / 洋服', back: 'ふく / ようふく (fuku / youfuku)', example: 'Quần áo / Đồ Âu' },
            { front: '眼鏡', back: 'めがね (megane)', example: 'Kính' },
            { front: '食べ物', back: 'たべもの (tabemono)', example: 'Đồ ăn' },
            { front: '飲み物', back: 'のみもの (nomimono)', example: 'Đồ uống' },
            { front: 'ご飯', back: 'ごはん (gohan)', example: 'Cơm' },
            { front: 'お弁当', back: 'おべんとう (obentou)', example: 'Cơm hộp' },
            { front: '肉', back: 'にく (niku)', example: 'Thịt' },
            { front: '牛肉', back: 'ぎゅうにく (gyuuniku)', example: 'Thịt bò' },
            { front: '豚肉', back: 'ぶたにく (butaniku)', example: 'Thịt lợn' },
            { front: '魚', back: 'さかな (sakana)', example: 'Cá' },
            { front: '卵', back: 'たまご (tamago)', example: 'Trứng' },
            { front: '野菜', back: 'やさい (yasai)', example: 'Rau củ' },
            { front: '果物', back: 'くだもの (kudamono)', example: 'Hoa quả' },
            { front: 'パン', back: 'パン (pan)', example: 'Bánh mỳ' },
            { front: '水', back: 'みず (mizu)', example: 'Nước' },
            { front: 'お茶', back: 'おちゃ (ocha)', example: 'Trà xanh' },
            { front: '紅茶', back: 'こうちゃ (koucha)', example: 'Hồng trà' },
            { front: 'コーヒー', back: 'コーヒー (koohii)', example: 'Cà phê' },
            { front: '牛乳', back: 'ぎゅうにゅう (gyuunyuu)', example: 'Sữa bò' },
            { front: 'お酒', back: 'おさけ (osake)', example: 'Rượu' },
            { front: 'ビール', back: 'ビール (biiru)', example: 'Bia' },
            { front: 'お菓子', back: 'おかし (okashi)', example: 'Bánh kẹo' },
            { front: '砂糖', back: 'さとう (satou)', example: 'Đường' },
            { front: '塩', back: 'しお (shio)', example: 'Muối' },
            { front: '醤油', back: 'しょうゆ (shouyu)', example: 'Nước tương' },
        ]
    },
    {
        title: 'ĐỊA ĐIỂM, VỊ TRÍ & PHƯƠNG TIỆN',
        description: 'Nơi chốn công cộng, phương hướng, vị trí và các phương tiện giao thông.',
        cards: [
            { front: 'ここ / そこ / あそこ', back: 'ここ / そこ / あそこ (koko / soko / asoko)', example: 'Ở đây / đó / kia' },
            { front: 'どこ', back: 'どこ (doko)', example: 'Ở đâu' },
            { front: 'こちら / そちら / あちら', back: 'こちら / そちら / あちら (kochira / sochira / achira)', example: 'Phía này / đó / kia' },
            { front: 'どちら / どっち', back: 'どちら / どっち (dochira / dotchi)', example: 'Phía nào, hướng nào' },
            { front: '学校', back: 'がっこう (gakkou)', example: 'Trường học' },
            { front: '大学', back: 'だいがく (daigaku)', example: 'Đại học' },
            { front: '病院', back: 'びょういん (byouin)', example: 'Bệnh viện' },
            { front: '会社', back: 'かいしゃ (kaisha)', example: 'Công ty' },
            { front: '銀行', back: 'ぎんこう (ginkou)', example: 'Ngân hàng' },
            { front: '空港', back: 'くうこう (kuukou)', example: 'Sân bay' },
            { front: '店', back: 'みせ (mise)', example: 'Cửa hàng' },
            { front: '本屋', back: 'ほんや (honya)', example: 'Hiệu sách' },
            { front: '喫茶店', back: 'きっさてん (kissaten)', example: 'Quán giải khát, cafe' },
            { front: 'レストラン', back: 'レストラン (resutoran)', example: 'Nhà hàng' },
            { front: 'スーパー', back: 'スーパー (suupaa)', example: 'Siêu thị' },
            { front: 'コンビニ', back: 'コンビニ (konbini)', example: 'Cửa hàng tiện lợi' },
            { front: '公園', back: 'こうえん (kouen)', example: 'Công viên' },
            { front: '庭', back: 'にわ (niwa)', example: 'Vườn' },
            { front: '美術館', back: 'びじゅつかん (bijutsukan)', example: 'Bảo tàng mỹ thuật' },
            { front: '市役所', back: 'しやくしょ (shiyakusho)', example: 'Tòa thị chính' },
            { front: '駐車場', back: 'ちゅうしゃじょう (chuushajou)', example: 'Bãi đỗ xe' },
            { front: '交差点', back: 'こうさてん (kousaten)', example: 'Ngã tư' },
            { front: '道', back: 'みち (michi)', example: 'Đường' },
            { front: '橋', back: 'はし (hashi)', example: 'Cầu' },
            { front: '海', back: 'うみ (umi)', example: 'Biển' },
            { front: '山', back: 'やま (yama)', example: 'Núi' },
            { front: '川', back: 'かわ (kawa)', example: 'Sông' },
            { front: 'いなか', back: 'いなか (inaka)', example: 'Nông thôn, quê' },
            { front: '上', back: 'うえ (ue)', example: 'Trên' },
            { front: '下', back: 'した (shita)', example: 'Dưới' },
            { front: '前', back: 'まえ (mae)', example: 'Trước' },
            { front: '後ろ', back: 'うしろ (ushiro)', example: 'Sau' },
            { front: '右', back: 'みぎ (migi)', example: 'Phải' },
            { front: '左', back: 'ひだり (hidari)', example: 'Trái' },
            { front: '中', back: 'なか (naka)', example: 'Trong' },
            { front: '外', back: 'そと (soto)', example: 'Ngoài' },
            { front: '隣', back: 'となり (tonari)', example: 'Bên cạnh' },
            { front: '近く', back: 'ちかく (chikaku)', example: 'Gần' },
            { front: '間', back: 'あいだ (aida)', example: 'Ở giữa' },
            { front: '奥', back: 'おく (oku)', example: 'Bên trong cùng' },
            { front: '車 / 自動車', back: 'くるま / じどうしゃ (kuruma / jidousha)', example: 'Ô tô' },
            { front: '電車', back: 'でんしゃ (densha)', example: 'Tàu điện' },
            { front: '地下鉄', back: 'ちかてつ (chikatetsu)', example: 'Tàu điện ngầm' },
            { front: '飛行機', back: 'ひこうき (hikouki)', example: 'Máy bay' },
            { front: '船', back: 'ふね (fune)', example: 'Tàu thủy' },
            { front: '自転車', back: 'じてんしゃ (jitensha)', example: 'Xe đạp' },
            { front: 'バイク', back: 'バイク (baiku)', example: 'Xe máy' },
            { front: 'バス', back: 'バス (basu)', example: 'Xe bus' },
            { front: 'タクシー', back: 'タクシー (takushii)', example: 'Taxi' },
        ]
    },
    {
        title: 'ĐỘNG TỪ (VERBS)',
        description: 'Các hành động hằng ngày, di chuyển, giao tiếp và sinh hoạt.',
        cards: [
            { front: '行く', back: 'いく (iku)', example: 'Đi' },
            { front: '来る', back: 'くる (kuru)', example: 'Đến' },
            { front: '帰る', back: 'かえる (kaeru)', example: 'Về' },
            { front: '食べる', back: 'たべる (taberu)', example: 'Ăn' },
            { front: '飲む', back: 'のむ (nomu)', example: 'Uống' },
            { front: '吸う', back: 'すう (suu)', example: 'Hút (thuốc)' },
            { front: '見る', back: 'みる (miru)', example: 'Xem, nhìn' },
            { front: '聞く', back: 'きく (kiku)', example: 'Nghe, hỏi' },
            { front: '読む', back: 'よむ (yomu)', example: 'Đọc' },
            { front: '書く', back: 'かく (kaku)', example: 'Viết' },
            { front: '買う', back: 'かう (kau)', example: 'Mua' },
            { front: '撮る', back: 'とる (toru)', example: 'Chụp (ảnh)' },
            { front: 'する', back: 'する (suru)', example: 'Làm, chơi' },
            { front: '会う', back: 'あう (au)', example: 'Gặp gỡ' },
            { front: '分かる', back: 'わかる (wakaru)', example: 'Hiểu, biết' },
            { front: '有る', back: 'ある (aru)', example: 'Có (Đồ vật)' },
            { front: '居る', back: 'いる (iru)', example: 'Có, ở (Người, động vật)' },
            { front: '休む', back: 'やすむ (yasumu)', example: 'Nghỉ ngơi' },
            { front: '起きる', back: 'おきる (okiru)', example: 'Thức dậy' },
            { front: '寝る', back: 'ねる (neru)', example: 'Ngủ' },
            { front: '働く', back: 'はたらく (hataraku)', example: 'Làm việc' },
            { front: '終わる', back: 'おわる (owaru)', example: 'Kết thúc' },
            { front: '教える', back: 'おしえる (oshieru)', example: 'Dạy, chỉ bảo' },
            { front: '習う', back: 'ならう (narau)', example: 'Học' },
            { front: '貸す', back: 'かす (kasu)', example: 'Cho mượn' },
            { front: '借りる', back: 'かりる (kariru)', example: 'Đi mượn' },
            { front: 'あげる', back: 'あげる (ageru)', example: 'Cho, tặng' },
            { front: '貰う', back: 'もらう (morau)', example: 'Nhận' },
            { front: '待つ', back: 'まつ (matsu)', example: 'Đợi, chờ' },
            { front: '持つ', back: 'もつ (motsu)', example: 'Cầm, mang' },
            { front: '急ぐ', back: 'いそぐ (isogu)', example: 'Gấp, vội' },
            { front: '呼ぶ', back: 'よぶ (yobu)', example: 'Gọi' },
            { front: '曲がる', back: 'まがる (magaru)', example: 'Rẽ, quẹo' },
            { front: '降る', back: 'ふる (furu)', example: 'Rơi (mưa, tuyết)' },
            { front: '止める', back: 'とめる (tomeru)', example: 'Dừng, đỗ' },
            { front: '見せる', back: 'みせる (miseru)', example: 'Cho xem' },
            { front: '開ける', back: 'あける (akeru)', example: 'Mở' },
            { front: '閉める', back: 'しめる (shimeru)', example: 'Đóng' },
            { front: 'つける', back: 'つける (tsukeru)', example: 'Bật (điện)' },
            { front: '消す', back: 'けす (kesu)', example: 'Tắt' },
            { front: '乗る', back: 'のる (noru)', example: 'Lên (xe)' },
            { front: '降りる', back: 'おりる (oriru)', example: 'Xuống (xe)' },
            { front: '乗り換える', back: 'のりかえる (norikaeru)', example: 'Đổi xe/tàu' },
            { front: '浴びる', back: 'あびる (abiru)', example: 'Tắm (vòi sen)' },
            { front: '入れる', back: 'いれる (ireru)', example: 'Cho vào' },
            { front: '出す', back: 'だす (dasu)', example: 'Lấy ra, nộp (báo cáo)' },
            { front: '入る', back: 'はいる (hairu)', example: 'Đi vào' },
            { front: '出る', back: 'でる (deru)', example: 'Đi ra' },
            { front: '歩く', back: 'あるく (aruku)', example: 'Đi bộ' },
            { front: '遊ぶ', back: 'あそぶ (asobu)', example: 'Chơi' },
            { front: '泳ぐ', back: 'およぐ (oyogu)', example: 'Bơi' },
            { front: '疲れる', back: 'つかれる (tsukareru)', example: 'Mệt mỏi' },
            { front: '作る', back: 'つくる (tsukuru)', example: 'Làm, chế tạo' },
            { front: '売る', back: 'うる (uru)', example: 'Bán' },
            { front: '知る', back: 'しる (shiru)', example: 'Biết' },
            { front: '住む', back: 'すむ (sumu)', example: 'Sống, ở' },
            { front: '辞める', back: 'やめる (yameru)', example: 'Bỏ, nghỉ việc' },
            { front: '思い出す', back: 'おもいだす (omoidasu)', example: 'Nhớ lại' },
            { front: '覚える', back: 'おぼえる (oboeru)', example: 'Nhớ, ghi nhớ' },
            { front: '忘れる', back: 'わすれる (wasureru)', example: 'Quên' },
            { front: 'なくす', back: 'なくす (nakusu)', example: 'Đánh mất' },
            { front: '払う', back: 'はらう (harau)', example: 'Trả tiền' },
            { front: '脱ぐ', back: 'ぬぐ (nugu)', example: 'Cởi (quần áo)' },
            { front: '触る', back: 'さわる (sawaru)', example: 'Chạm, sờ' },
            { front: '渡る', back: 'わたる (wataru)', example: 'Băng qua (đường, cầu)' },
        ]
    },
    {
        title: 'TÍNH TỪ (ADJECTIVES)',
        description: 'Tính chất, cảm xúc, nhiệt độ, kích thước và trạng thái.',
        cards: [
            { front: '大きい', back: 'おおきい (ookii)', example: 'To, lớn' },
            { front: '小さい', back: 'ちいさい (chiisai)', example: 'Nhỏ, bé' },
            { front: '新しい', back: 'あたらしい (atarashii)', example: 'Mới' },
            { front: '古い', back: 'ふるい (furui)', example: 'Cũ' },
            { front: '高い', back: 'たかい (takai)', example: 'Cao, đắt' },
            { front: '安い', back: 'やすい (yasui)', example: 'Rẻ' },
            { front: '良い', back: 'よい / いい (yoi / ii)', example: 'Tốt' },
            { front: '悪い', back: 'わるい (warui)', example: 'Xấu, tồi' },
            { front: '難しい', back: 'むずかしい (muzukashii)', example: 'Khó' },
            { front: '易しい', back: 'やさしい (yasashii)', example: 'Dễ' },
            { front: '遠い', back: 'とおい (tooi)', example: 'Xa' },
            { front: '近い', back: 'ちかい (chikai)', example: 'Gần' },
            { front: '美味しい', back: 'おいしい (oishii)', example: 'Ngon' },
            { front: '忙しい', back: 'いそがしい (isogashii)', example: 'Bận rộn' },
            { front: '楽しい', back: 'たのしい (tanoshii)', example: 'Vui vẻ' },
            { front: '暖かい', back: 'あたたかい (atatakai)', example: 'Ấm áp' },
            { front: '涼しい', back: 'すずしい (suzushii)', example: 'Mát mẻ' },
            { front: '暑い', back: 'あつい (atsui)', example: 'Nóng' },
            { front: '寒い', back: 'さむい (samui)', example: 'Lạnh' },
            { front: '甘い', back: 'あまい (amai)', example: 'Ngọt' },
            { front: '辛い', back: 'からい (karai)', example: 'Cay' },
            { front: '重い', back: 'おもい (omoi)', example: 'Nặng' },
            { front: '軽い', back: 'かるい (karui)', example: 'Nhẹ' },
            { front: '広い', back: 'ひろい (hiroi)', example: 'Rộng' },
            { front: '狭い', back: 'せまい (semai)', example: 'Hẹp' },
            { front: '長い', back: 'ながい (nagai)', example: 'Dài' },
            { front: '短い', back: 'みじかい (mijikai)', example: 'Ngắn' },
            { front: '痛い', back: 'いたい (itai)', example: 'Đau' },
            { front: '欲しい', back: 'ほしい (hoshii)', example: 'Muốn có' },
            { front: '寂しい', back: 'さびしい (sabishii)', example: 'Buồn, cô đơn' },
            { front: '眠い', back: 'ねむい (nemui)', example: 'Buồn ngủ' },
            { front: '好き [な]', back: 'すき (suki)', example: 'Thích' },
            { front: '嫌い [な]', back: 'きらい (kirai)', example: 'Ghét' },
            { front: '上手 [な]', back: 'じょうず (jouzu)', example: 'Giỏi, khéo' },
            { front: '下手 [な]', back: 'へた (heta)', example: 'Kém, dốt' },
            { front: '静か [な]', back: 'しずか (shizuka)', example: 'Yên tĩnh' },
            { front: '賑やか [な]', back: 'にぎやか (nigiyaka)', example: 'Náo nhiệt' },
            { front: '親切 [な]', back: 'しんせつ (shinsetsu)', example: 'Tốt bụng' },
            { front: '元気 [な]', back: 'げんき (genki)', example: 'Khỏe mạnh' },
            { front: '便利 [な]', back: 'べんり (benri)', example: 'Tiện lợi' },
            { front: '不便 [な]', back: 'ふべん (fuben)', example: 'Bất tiện' },
            { front: '簡単 [な]', back: 'かんたん (kantan)', example: 'Đơn giản' },
            { front: '暇 [な]', back: 'ひま (hima)', example: 'Rảnh rỗi' },
            { front: '色々 [な]', back: 'いろいろ (iroiro)', example: 'Nhiều, đa dạng' },
            { front: '大変 [な]', back: 'たいへん (taihen)', example: 'Vất vả' },
            { front: '大丈夫 [な]', back: 'だいじょうぶ (daijoubu)', example: 'Không sao' },
        ]
    },
    {
        title: 'TRẠNG TỪ & CÂU GIAO TIẾP',
        description: 'Trạng từ chỉ mức độ, tần suất, liên từ và các mẫu câu giao tiếp cơ bản.',
        cards: [
            { front: 'とても', back: 'とても (totemo)', example: 'Rất' },
            { front: '大変', back: 'たいへん (taihen)', example: 'Rất, vô cùng' },
            { front: '少し', back: 'すこし (sukoshi)', example: 'Một chút, ít' },
            { front: 'ちょっと', back: 'ちょっと (chotto)', example: 'Một chút' },
            { front: 'たくさん', back: 'たくさん (takusan)', example: 'Nhiều' },
            { front: '大体', back: 'だいたい (daitai)', example: 'Đại khái' },
            { front: '全然', back: 'ぜんぜん (zenzen)', example: 'Hoàn toàn không (đi với phủ định)' },
            { front: 'あまり', back: 'あまり (amari)', example: 'Không... lắm (đi với phủ định)' },
            { front: 'いつも', back: 'いつも (itsumo)', example: 'Luôn luôn' },
            { front: 'よく', back: 'よく (yoku)', example: 'Thường xuyên / Rõ, tốt' },
            { front: '時々', back: 'ときどき (tokidoki)', example: 'Thỉnh thoảng' },
            { front: 'もう', back: 'もう (mou)', example: 'Đã ~ rồi' },
            { front: 'まだ', back: 'まだ (mada)', example: 'Vẫn chưa' },
            { front: 'だんだん', back: 'だんだん (dandan)', example: 'Dần dần' },
            { front: 'きっと', back: 'きっと (kitto)', example: 'Chắc chắn' },
            { front: '多分', back: 'たぶん (tabun)', example: 'Có lẽ' },
            { front: 'なかなか', back: 'なかなか (nakanaka)', example: 'Mãi mà không... (đi với phủ định)' },
            { front: 'ぜひ', back: 'ぜひ (zehi)', example: 'Nhất định' },
            { front: '一緒に', back: 'いっしょに (issho ni)', example: 'Cùng nhau' },
            { front: '一人で', back: 'ひとりで (hitori de)', example: 'Một mình' },
            { front: '全部で', back: 'ぜんぶで (zenbu de)', example: 'Tổng cộng' },
            { front: '~だけ', back: 'だけ (dake)', example: 'Chỉ ~' },
            { front: 'ずっと', back: 'ずっと (zutto)', example: 'Suốt / Hơn hẳn (so sánh)' },
            { front: '初めて', back: 'はじめて (hajimete)', example: 'Lần đầu tiên' },
            { front: 'これから', back: 'これから (korekara)', example: 'Từ bây giờ' },
            { front: 'まず', back: 'まず (mazu)', example: 'Trước hết' },
            { front: '次に', back: 'つぎに (tsugi ni)', example: 'Tiếp theo' },
            { front: '後で', back: 'あとで (ato de)', example: 'Sau đó' },
            { front: '一生懸命', back: 'いっしょうけんめい (isshoukenmei)', example: 'Cố gắng hết sức' },
            { front: 'ほんの気持ち', back: 'ほんのきもち (hon no kimochi)', example: 'Chút lòng thành' },
            { front: 'どうぞよろしくお願いします', back: 'どうぞよろしくお願いします (douzo yoroshiku onegaishimasu)', example: 'Rất mong được giúp đỡ' },
            { front: '失礼ですが', back: 'しつれいですが (shitsurei desu ga)', example: 'Xin lỗi (khi hỏi thông tin)' },
            { front: 'お名前は', back: 'おなまえは (onamae wa)', example: 'Tên bạn là gì?' },
            { front: 'そうですか', back: 'そうですか (sou desu ka)', example: 'Vậy à / Thế à.' },
            { front: 'いいですよ', back: 'いいですよ (ii desu yo)', example: 'Được đấy.' },
            { front: '気を付ける', back: 'きをつける (ki o tsukeru)', example: 'Chú ý, cẩn thận' },
            { front: 'おめでとうございます', back: 'おめでとうございます (omedetou gozaimasu)', example: 'Chúc mừng!' },
        ]
    }
];