// lib/n5TestData.ts

export interface TestItem {
    kana: string;
    romaji: string;
    meaning: string;
}

export const WEEK1_TEST_DATA: TestItem[] = [
    { kana: 'ひと', romaji: 'hito', meaning: 'người' },
    { kana: 'いす', romaji: 'isu', meaning: 'cái ghế' },
    { kana: 'はる', romaji: 'haru', meaning: 'mùa xuân' },
    { kana: 'なつ', romaji: 'natsu', meaning: 'mùa hè' },
    { kana: 'あき', romaji: 'aki', meaning: 'mùa thu' },
    { kana: 'ふゆ', romaji: 'fuyu', meaning: 'mùa đông' },
    { kana: 'あし', romaji: 'ashi', meaning: 'chân' },
    { kana: 'め', romaji: 'me', meaning: 'mắt' },
    { kana: 'て', romaji: 'te', meaning: 'tay' },
    { kana: 'くち', romaji: 'kuchi', meaning: 'miệng' },
    { kana: 'かお', romaji: 'kao', meaning: 'khuôn mặt' },
    { kana: 'みみ', romaji: 'mimi', meaning: 'tai' },
    { kana: 'いえ', romaji: 'ie', meaning: 'ngôi nhà' },
    { kana: 'にわ', romaji: 'niwa', meaning: 'sân vườn' },
    { kana: 'かみ', romaji: 'kami', meaning: 'tóc / giấy' },
    { kana: 'あい', romaji: 'ai', meaning: 'tình yêu' },
    { kana: 'いう', romaji: 'iu', meaning: 'nói' },
    { kana: 'うえ', romaji: 'ue', meaning: 'bên trên' },
    { kana: 'あお', romaji: 'ao', meaning: 'màu xanh dương' },
    { kana: 'かき', romaji: 'kaki', meaning: 'quả hồng' },
    { kana: 'きく', romaji: 'kiku', meaning: 'nghe / hoa cúc' },
    { kana: 'いけ', romaji: 'ike', meaning: 'cái ao' },
    { kana: 'こえ', romaji: 'koe', meaning: 'giọng nói' },
    { kana: 'さけ', romaji: 'sake', meaning: 'rượu sake / cá hồi' },
    { kana: 'あせ', romaji: 'ase', meaning: 'mồ hôi' },
    { kana: 'うし', romaji: 'ushi', meaning: 'con bò' },
    { kana: 'すいか', romaji: 'suika', meaning: 'dưa hấu' },
    { kana: 'せかい', romaji: 'sekai', meaning: 'thế giới' },
    { kana: 'そこ', romaji: 'soko', meaning: 'chỗ đó' },
    { kana: 'いぬ', romaji: 'inu', meaning: 'con chó' },
    { kana: 'ねこ', romaji: 'neko', meaning: 'con mèo' },
    { kana: 'とり', romaji: 'tori', meaning: 'con chim' },
    { kana: 'くるま', romaji: 'kuruma', meaning: 'ô tô' },
    { kana: 'さくら', romaji: 'sakura', meaning: 'hoa anh đào' },
    { kana: 'はな', romaji: 'hana', meaning: 'bông hoa' },
    { kana: 'ほし', romaji: 'hoshi', meaning: 'ngôi sao' },
    { kana: 'つき', romaji: 'tsuki', meaning: 'mặt trăng' },
    { kana: 'ゆき', romaji: 'yuki', meaning: 'tuyết' },
    { kana: 'あめ', romaji: 'ame', meaning: 'mưa / kẹo' },
    { kana: 'やま', romaji: 'yama', meaning: 'ngọn núi' },
    { kana: 'かわ', romaji: 'kawa', meaning: 'con sông' },
    { kana: 'うみ', romaji: 'umi', meaning: 'biển' },
    { kana: 'そら', romaji: 'sora', meaning: 'bầu trời' },
    { kana: 'くも', romaji: 'kumo', meaning: 'đám mây / con nhện' },
    { kana: 'かぜ', romaji: 'kaze', meaning: 'cơn gió / cảm lạnh' },
    { kana: 'まど', romaji: 'mado', meaning: 'cửa sổ' },
    { kana: 'つくえ', romaji: 'tsukue', meaning: 'cái bàn' },
    { kana: 'ほん', romaji: 'hon', meaning: 'quyển sách' },
    { kana: 'かばん', romaji: 'kaban', meaning: 'cái cặp / túi xách' },
    { kana: 'みず', romaji: 'mizu', meaning: 'nước' },
    { kana: 'たべもの', romaji: 'tabemono', meaning: 'đồ ăn' },
    { kana: 'のみもの', romaji: 'nomimono', meaning: 'đồ uống' },
    { kana: 'くだもの', romaji: 'kudamono', meaning: 'trái cây' },
    { kana: 'さいふ', romaji: 'saifu', meaning: 'cái ví' },
    { kana: 'ぼうし', romaji: 'boushi', meaning: 'cái mũ' },
    { kana: 'くつ', romaji: 'kutsu', meaning: 'đôi giày' },
    { kana: 'めがね', romaji: 'megane', meaning: 'kính mắt' },
    { kana: 'かさ', romaji: 'kasa', meaning: 'cái ô / dù' },
    { kana: 'とけい', romaji: 'tokei', meaning: 'đồng hồ' },
    { kana: 'おんがく', romaji: 'ongaku', meaning: 'âm nhạc' },
    { kana: 'がくせい', romaji: 'gakusei', meaning: 'học sinh / sinh viên' },
    { kana: 'せんせい', romaji: 'sensei', meaning: 'giáo viên' },
    { kana: 'がっこう', romaji: 'gakkou', meaning: 'trường học' },
    { kana: 'かいしゃ', romaji: 'kaisha', meaning: 'công ty' },
    { kana: 'びょういん', romaji: 'byouin', meaning: 'bệnh viện' },
    { kana: 'ぎんこう', romaji: 'ginkou', meaning: 'ngân hàng' },
    { kana: 'ゆうびんきょく', romaji: 'yuubinkyoku', meaning: 'bưu điện' },
    { kana: 'としょかん', romaji: 'toshokan', meaning: 'thư viện' },
    { kana: 'えいがかん', romaji: 'eigakan', meaning: 'rạp chiếu phim' },
    { kana: 'びじゅつかん', romaji: 'bijutsukan', meaning: 'bảo tàng mỹ thuật' },
    { kana: 'しゃしん', romaji: 'shashin', meaning: 'bức ảnh' },
    { kana: 'おちゃ', romaji: 'ocha', meaning: 'trà' },
    { kana: 'ぎゅうにゅう', romaji: 'gyuunyuu', meaning: 'sữa bò' },
    { kana: 'じてんしゃ', romaji: 'jitensha', meaning: 'xe đạp' },
    { kana: 'きょう', romaji: 'kyou', meaning: 'hôm nay' },
    { kana: 'あした', romaji: 'ashita', meaning: 'ngày mai' },
    { kana: 'あさって', romaji: 'asatte', meaning: 'ngày kia' },
    { kana: 'きのう', romaji: 'kinou', meaning: 'hôm qua' },
    { kana: 'おととい', romaji: 'ototoi', meaning: 'hôm kia' },
    { kana: 'けさ', romaji: 'kesa', meaning: 'sáng nay' },
    { kana: 'こんばん', romaji: 'konban', meaning: 'tối nay' },
    { kana: 'まいにち', romaji: 'mainichi', meaning: 'mỗi ngày' },
    { kana: 'まいあさ', romaji: 'maiasa', meaning: 'mỗi sáng' },
    { kana: 'まいばん', romaji: 'maiban', meaning: 'mỗi tối' },
    { kana: 'らいしゅう', romaji: 'raishuu', meaning: 'tuần sau' },
    { kana: 'せんしゅう', romaji: 'senshuu', meaning: 'tuần trước' },
    { kana: 'こんしゅう', romaji: 'konshuu', meaning: 'tuần này' },
    { kana: 'らいげつ', romaji: 'raigetsu', meaning: 'tháng sau' },
    { kana: 'せんげつ', romaji: 'sengetsu', meaning: 'tháng trước' },
    { kana: 'こんげつ', romaji: 'kongetsu', meaning: 'tháng này' },
    { kana: 'らいねん', romaji: 'rainen', meaning: 'năm sau' },
    { kana: 'きょねん', romaji: 'kyonen', meaning: 'năm ngoái' },
    { kana: 'ことし', romaji: 'kotoshi', meaning: 'năm nay' },
    { kana: 'たんじょうび', romaji: 'tanjoubi', meaning: 'sinh nhật' },
    { kana: 'ひこうき', romaji: 'hikouki', meaning: 'máy bay' },
    { kana: 'しんかんせん', romaji: 'shinkansen', meaning: 'tàu siêu tốc shinkansen' },
    { kana: 'おかあさん', romaji: 'okaasan', meaning: 'mẹ (người khác)' },
    { kana: 'おとうさん', romaji: 'otousan', meaning: 'bố (người khác)' },
    { kana: 'おにいさん', romaji: 'oniisan', meaning: 'anh trai (người khác)' },
    { kana: 'おねえさん', romaji: 'oneesan', meaning: 'chị gái (người khác)' },
];

export const WEEK2_TEST_DATA: TestItem[] = [
    { kana: 'ドア', romaji: 'doa', meaning: 'cửa ra vào' },
    { kana: 'ペン', romaji: 'pen', meaning: 'bút mực' },
    { kana: 'パン', romaji: 'pan', meaning: 'bánh mì' },
    { kana: 'メモ', romaji: 'memo', meaning: 'ghi chú' },
    { kana: 'バス', romaji: 'basu', meaning: 'xe buýt' },
    { kana: 'ガス', romaji: 'gasu', meaning: 'khí ga' },
    { kana: 'コップ', romaji: 'koppu', meaning: 'cái cốc' },
    { kana: 'ベッド', romaji: 'beddo', meaning: 'cái giường' },
    { kana: 'ノート', romaji: 'nooto', meaning: 'vở' },
    { kana: 'ビル', romaji: 'biru', meaning: 'tòa nhà' },
    { kana: 'ベル', romaji: 'beru', meaning: 'cái chuông' },
    { kana: 'カメラ', romaji: 'kamera', meaning: 'máy ảnh' },
    { kana: 'テレビ', romaji: 'terebi', meaning: 'tivi' },
    { kana: 'ラジオ', romaji: 'rajio', meaning: 'đài radio' },
    { kana: 'トイレ', romaji: 'toire', meaning: 'nhà vệ sinh' },
    { kana: 'クラス', romaji: 'kurasu', meaning: 'lớp học' },
    { kana: 'テスト', romaji: 'tesuto', meaning: 'bài kiểm tra' },
    { kana: 'ホテル', romaji: 'hoteru', meaning: 'khách sạn' },
    { kana: 'ツアー', romaji: 'tsuaa', meaning: 'chuyến du lịch' },
    { kana: 'ビザ', romaji: 'biza', meaning: 'visa' },
    { kana: 'ゲーム', romaji: 'geemu', meaning: 'trò chơi' },
    { kana: 'アプリ', romaji: 'apuri', meaning: 'ứng dụng' },
    { kana: 'メール', romaji: 'meeru', meaning: 'email' },
    { kana: 'コピー', romaji: 'kopii', meaning: 'bản sao' },
    { kana: 'ページ', romaji: 'peeji', meaning: 'trang (sách)' },
    { kana: 'スープ', romaji: 'suupu', meaning: 'món súp' },
    { kana: 'サラダ', romaji: 'sarada', meaning: 'món xà lách (salad)' },
    { kana: 'ナイフ', romaji: 'naifu', meaning: 'con dao' },
    { kana: 'フォーク', romaji: 'fooku', meaning: 'cái dĩa' },
    { kana: 'スプーン', romaji: 'supuun', meaning: 'cái thìa' },
    { kana: 'シャツ', romaji: 'shatsu', meaning: 'áo sơ mi' },
    { kana: 'パンツ', romaji: 'pantsu', meaning: 'quần đùi / quần lót' },
    { kana: 'スカート', romaji: 'sukaato', meaning: 'chân váy' },
    { kana: 'ドレス', romaji: 'doresu', meaning: ' váy liền' },
    { kana: 'コート', romaji: 'kooto', meaning: 'áo khoác' },
    { kana: 'セーター', romaji: 'seetaa', meaning: 'áo len' },
    { kana: 'ネクタイ', romaji: 'nekutai', meaning: 'cà vạt' },
    { kana: 'バッグ', romaji: 'baggu', meaning: 'túi xách' },
    { kana: 'ガラス', romaji: 'garasu', meaning: 'kính (chất liệu)' },
    { kana: 'フィルム', romaji: 'firumu', meaning: 'cuộn phim' },
    { kana: 'スイッチ', romaji: 'suicchi', meaning: 'công tắc' },
    { kana: 'エアコン', romaji: 'eakon', meaning: 'máy điều hòa' },
    { kana: 'リモコン', romaji: 'rimokon', meaning: 'điều khiển từ xa' },
    { kana: 'プール', romaji: 'puuru', meaning: 'hồ bơi' },
    { kana: 'テニス', romaji: 'tenisu', meaning: 'quần vợt' },
    { kana: 'サッカー', romaji: 'sakkaa', meaning: 'bóng đá' },
    { kana: 'ゴルフ', romaji: 'gorufu', meaning: 'đánh gôn' },
    { kana: 'スキー', romaji: 'sukii', meaning: 'trượt tuyết' },
    { kana: 'スケート', romaji: 'sukeeto', meaning: 'trượt băng' },
    { kana: 'ギター', romaji: 'gitaa', meaning: 'đàn ghi ta' },
    { kana: 'ピアノ', romaji: 'piano', meaning: 'đàn piano' },
    { kana: 'ダンス', romaji: 'dansu', meaning: 'khiêu vũ' },
    { kana: 'ボール', romaji: 'booru', meaning: 'quả bóng' },
    { kana: 'ミルク', romaji: 'miruku', meaning: 'sữa' },
    { kana: 'ジュース', romaji: 'juusu', meaning: 'nước ép' },
    { kana: 'ビール', romaji: 'biiru', meaning: 'bia' },
    { kana: 'ワイン', romaji: 'wain', meaning: 'rượu vang' },
    { kana: 'チーズ', romaji: 'chiizu', meaning: 'phô mai' },
    { kana: 'ケーキ', romaji: 'keeki', meaning: 'bánh ngọt' },
    { kana: 'コーヒー', romaji: 'koohii', meaning: 'cà phê' },
    { kana: 'スーパー', romaji: 'suupaa', meaning: 'siêu thị' },
    { kana: 'デパート', romaji: 'depaato', meaning: 'trung tâm thương mại' },
    { kana: 'コンビニ', romaji: 'konbini', meaning: 'cửa hàng tiện lợi' },
    { kana: 'レストラン', romaji: 'resutoran', meaning: 'nhà hàng' },
    { kana: 'アパート', romaji: 'apaato', meaning: 'căn hộ' },
    { kana: 'マンション', romaji: 'manshon', meaning: 'chung cư cao cấp' },
    { kana: 'リビング', romaji: 'ribingu', meaning: 'phòng khách' },
    { kana: 'キッチン', romaji: 'kicchin', meaning: 'nhà bếp' },
    { kana: 'バルコニー', romaji: 'barukonii', meaning: 'ban công' },
    { kana: 'シャワー', romaji: 'shawaa', meaning: 'vòi hoa sen' },
    { kana: 'タクシー', romaji: 'takushii', meaning: 'xe taxi' },
    { kana: 'トラック', romaji: 'torakku', meaning: 'xe tải' },
    { kana: 'オートバイ', romaji: 'ootobai', meaning: 'xe máy' },
    { kana: 'エンジン', romaji: 'enjin', meaning: 'động cơ' },
    { kana: 'タイヤ', romaji: 'taiya', meaning: 'lốp xe' },
    { kana: 'ガソリン', romaji: 'gasorin', meaning: 'xăng' },
    { kana: 'パソコン', romaji: 'pasokon', meaning: 'máy tính cá nhân' },
    { kana: 'スマホ', romaji: 'sumaho', meaning: 'điện thoại thông minh' },
    { kana: 'ニュース', romaji: 'nyuusu', meaning: 'tin tức' },
    { kana: 'チケット', romaji: 'chiketto', meaning: 'vé' },
    { kana: 'センター', romaji: 'sentaa', meaning: 'trung tâm' },
    { kana: 'カレンダー', romaji: 'karendaa', meaning: 'tờ lịch' },
    { kana: 'ポスター', romaji: 'posutaa', meaning: 'áp phích' },
    { kana: 'メッセージ', romaji: 'messeeji', meaning: 'tin nhắn' },
    { kana: 'トラブル', romaji: 'toraburu', meaning: 'rắc rối' },
    { kana: 'チャンス', romaji: 'chansu', meaning: 'cơ hội' },
    { kana: 'アイデア', romaji: 'aidea', meaning: 'ý tưởng' },
    { kana: 'デザイン', romaji: 'dezain', meaning: 'thiết kế' },
    { kana: 'パスポート', romaji: 'pasupooto', meaning: 'hộ chiếu' },
    { kana: 'エレベーター', romaji: 'erebeetaa', meaning: 'thang máy' },
    { kana: 'エスカレーター', romaji: 'esukareetaa', meaning: 'thang cuốn' },
    { kana: 'プラスチック', romaji: 'purasuchikku', meaning: 'nhựa' },
    { kana: 'インターネット', romaji: 'intaanetto', meaning: 'mạng internet' },
    { kana: 'チョコレート', romaji: 'chokoreeto', meaning: 'sô cô la' },
    { kana: 'ハンバーガー', romaji: 'hanbaagaa', meaning: 'bánh bơ-gơ' },
    { kana: 'アイスクリーム', romaji: 'aisukuriimu', meaning: 'kem' },
    { kana: 'スーツケース', romaji: 'suutsukeesu', meaning: 'va li' },
    { kana: 'スポーツ', romaji: 'supootsu', meaning: 'thể thao' },
    { kana: 'アルバイト', romaji: 'arubaito', meaning: 'việc làm thêm' },
    { kana: 'ボランティア', romaji: 'borantia', meaning: 'tình nguyện viên' },
];

function getUniqueData(data: TestItem[]): TestItem[] {
    const map = new Map<string, TestItem>();
    data.forEach(item => {
        // Only add if kana is valid Japanese characters (Hiragana, Katakana, Kanji) and long vowel mark
        if (item.kana && /^[\u3040-\u309F\u30A0-\u30FF\u4E00-\u9FAF\u30FC]+$/.test(item.kana)) {
            map.set(item.kana, item);
        }
    });
    return Array.from(map.values());
}

export const UNIQUE_WEEK1_TEST_DATA = getUniqueData(WEEK1_TEST_DATA);
export const UNIQUE_WEEK2_TEST_DATA = getUniqueData(WEEK2_TEST_DATA);
